# from .prompts import (
#   SYNTHESIZER_INSTRUCTION,
#   ECONOMIC_AGENT_INSTRUCTION,
#   HISTORICAL_AGENT_INSTRUCTION,
#   NEWS_AGENT_INSTRUCTION,
#   POLITICAL_AGENT_INSTRUCTION
# )
from . import prompts